### PR TITLE
Bug Fixes for 123,124,125,126,129 and 130

### LINKED ISSUE #124: internal error during metadownload if peer set metadata_size too large
During a meta download a peer specifies the length of the metadata via the key metadata_size. A peer can send a very large (or negative) number as the metadata_size. When the client attempts to check how many bytes it has left for this file an internal error is thrown. Attempting to remove the torrent will cause FileList::bytes_left to be called. 

Extension Handshake Setting metadata_size to -1:
```
d1:md11:ut_metadatai3ee13:metadata_sizei-1ee
```

```
FileList::left_bytes
...
  uint64_t left = size_bytes() - completed_bytes();
  if (left > ((uint64_t)1 << 60))
    throw internal_error("FileList::bytes_left() is too large.", data()->hash());
...
```
```
(gdb) p size_bytes()
$1 = 107339822789768
```
```
Caught internal_error: FileList::bytes_left() is too large. [#FB88BA396DD408BCE51F41AEAA71BE695F60FA87]
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libasan.so.1(backtrace+0x49) [0x7effcff5daf9]
/usr/local/lib64/libtorrent.so.19(_ZN7torrent14internal_error10initializeERKSs+0xd4) [0x7effd177b074]
/usr/local/lib64/libtorrent.so.19(_ZN7torrent14internal_errorC2EPKcRKNS_10HashStringE+0xeb) [0x7effd17bdf3b]
/usr/local/lib64/libtorrent.so.19(_ZNK7torrent8FileList10left_bytesEv+0xef) [0x7effd17b7aaf]
/usr/local/lib64/libtorrent.so.19(_ZNSt5_BindIFSt7_Mem_fnIMN7torrent8FileListEKFmvEEPS2_EE6__callImIEILm0EEEET_OSt5tupleIIDpT0_EESt12_Index_tupleIIXspT1_EEE+0x40) [0x7effd1892580]
/usr/local/lib64/libtorrent.so.19(_ZNSt5_BindIFSt7_Mem_fnIMN7torrent8FileListEKFmvEEPS2_EEclIIEmEET0_DpOT_+0x20) [0x7effd18925c0]
/usr/local/lib64/libtorrent.so.19(+0x29a710) [0x7effd18ec710]
/usr/local/lib64/libtorrent.so.19(_ZN7torrent11TrackerList10send_stateEPNS_7TrackerEi+0x15c) [0x7effd179ec7c]
/usr/local/lib64/libtorrent.so.19(_ZN7torrent17TrackerController15send_stop_eventEv+0x293) [0x7effd179c893]
/usr/local/lib64/libtorrent.so.19(_ZN7torrent8Download4stopEi+0x1a4) [0x7effd17750f4]
rtorrent() [0x553acb]
rtorrent() [0x49363d]
rtorrent() [0x495362]
rtorrent() [0x4953ea]
rtorrent() [0x495456]
rtorrent() [0x5aae95]
rtorrent() [0x5aaf14]
rtorrent() [0x5aeb38]
rtorrent() [0x5b072f]
rtorrent() [0x5c450f]
```

### PR DESCRIPTION
**Pull request by RealAlexJones**
Fixes for #123 #124 #125 #126 #129 #130 

One that I'm not too sure about is the change to left_bytes where I remove the restriction of left being < 1 << 60. This is to fix #124 where a peer during a meta download can set the size to be very large. I'm not sure which case that restriction was attempting to prevent.

### CODE REVIEW

File: src/dht/dht_server.cc [hunk 1]
```diff
@@ -743,6 +743,11 @@ DhtServer::event_read() {
       if (!message[key_t].is_raw_string())
         throw dht_error(dht_error_protocol, "No transaction ID");
 
+	  //Check transaction id length to avoid use of it in dht_error if invalid
+	  if(message[key_t].as_string().size() > 20) {
+		  throw network_error();
+	  }
```
Comment (rakshasa) [inline src/dht/dht_server.cc]: Please try to follow the code style, e.g. use spaces, not tabs. Properly format the comment with a leading space and punctuation.

Use 'as_raw_string().size()' as that doesn't require a conversion to std::string.

Also use dht_error_protocol, not network_error.

File: src/torrent/data/file_list.cc [hunk 2]
```diff
@@ -155,9 +155,6 @@ uint64_t
 FileList::left_bytes() const {
   uint64_t left = size_bytes() - completed_bytes();
 
-  if (left > ((uint64_t)1 << 60))
-    throw internal_error("FileList::bytes_left() is too large.", data()->hash());
-
```
Comment (rakshasa) [inline src/torrent/data/file_list.cc]: You are treating the symptom, not the disease. The above check is there to catch issues in other parts of the code, notably that we don't have a proper check in 'DownloadMain::set_metadata_size' that checks if the size is zero or more than a reasonable size.

In the case of metadata sizes, (1 << 26) or 64Mb seems a good upper limit.

File: src/dht/dht_server.cc (hunk 1 above)
Comment (rakshasa) [inline src/dht/dht_server.cc]: In that case also add the length check to 'create_error' so that it doesn't try to copy the key.

File: src/dht/dht_server.cc [hunk 3]
```diff
@@ -597,7 +597,7 @@ void
 DhtServer::create_error(const DhtMessage& req, const rak::socket_address* sa, int num, const char* msg) {
   DhtMessage error;
 
-  if (req[key_t].is_raw_bencode() || req[key_t].is_raw_string())
+  if ((req[key_t].is_raw_bencode() || req[key_t].is_raw_string()) && req[key_t].as_raw_string().size < 20)
```
Comment (rakshasa) [inline src/dht/dht_server.cc]: The parenthesis placement is wrong, you can't call as_raw_string on is_raw_bencode.

Comment (RealAlexJones) [inline src/dht/dht_server.cc]: is there ever a case where key_t will be raw_bencode and not a raw_string? 

The key is defined as t*S which will only ever be populated with raw_string

File: src/dht/dht_server.cc [hunk 4]
```diff
@@ -597,7 +597,8 @@ void
 DhtServer::create_error(const DhtMessage& req, const rak::socket_address* sa, int num, const char* msg) {
   DhtMessage error;
 
-  if ((req[key_t].is_raw_bencode() || req[key_t].is_raw_string()) && req[key_t].as_raw_string().size() < 20)
+  if ((req[key_t].is_raw_bencode() && req[key_t].as_raw_bencode().size() < 20) ||
```
Comment (rakshasa) [inline src/dht/dht_server.cc]: If the key is 20 bytes long string, then the bencode version of it will be '20:<20*bytes>" which is 23 bytes.

However the key can be more than 20 char long strings, so perhaps we should use e.g. 64 and 67 as the max lengths.

File: src/dht/dht_server.cc [hunk 5]
```diff
@@ -597,7 +597,8 @@ void
...
+		  (req[key_t].is_raw_string() && req[key_t].as_raw_string().size() < 20))
```
Comment (rakshasa) [inline src/dht/dht_server.cc]: If the key is 20 bytes long string, then the bencode version of it will be '20:<20*bytes>" which is 23 bytes.

However the key can be more than 20 char long strings, so perhaps we should use e.g. 64 and 67 as the max lengths.

Comment (rakshasa) [inline src/dht/dht_server.cc]: The internets is somewhat ambiguous about what the key can be, so I guess we can make the assumption that it's always a raw_string since the rest of the code assumes it.
